### ISSUE TITLE
BlurModal hide does not cancel the blurModal view, appears on rotate

### ISSUE THREAD

**Issue by sundialsoft** [rnystrom/RNBlurModalView#13]
When the view is hidden then the app rotated the whole screen gets covered in a blurred view with no alert on it. Everything behind the blur is working. I'm needing to nil the BlurModal view after I hide it to stop this happening.

**Comment by ansani** [comment]
This seems to appears ONLY when you call directly the "hide" method, not when you press the close button. I'm investigating on this issue because I've same behavior on my app ;)

[UPDATE: totally wrong. Issue is present EVEN when you press the close button].

[UPDATE x2: BUG FOUND!!!!!]
It appears ONLY when RNBlurModalView _is_ global!
If you declare RNBlurModalView locally, issue disappears :)

**Comment by ansani** [comment]
Just made a Pull Request to fix this issue

**Comment by rnystrom** [comment]
Awesome, thank you!
