### ISSUE TITLE
White background instead of blur.

### ISSUE THREAD

**Issue by mumensh** [rnystrom/RNBlurModalView#24]
First of all, awesome controller, great work.

I'm facing a problem when using it, the modal displaying with a white background, I've added it to a cocos2d project and used it like this

modal = [[RNBlurModalView alloc] initWithView:view];
[modal show];

What is the problem!?

**Comment by rnystrom** [comment]
The problem is likely because Cocos2D isn't using UIKit, it's OpenGL (I believe?). This line https://github.com/rnystrom/RNBlurModalView/blob/master/RNBlurModalView.m#L603-L614 is what creates a screenshot of the current view. That might be the problem. I've never intended to support OpenGL or Cocos2D so I'm not likely to add it. I'd probably take a pull request to fix this.

Look up how Cocos2D does it. If it's something simple like an OpenGL layer, getting the screenshot is fairly simple.
